import { RatRaceEnum } from '@/models/race/IRatRace';

export const ratRaceList: { idx: number; type: RatRaceEnum }[] = [
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.DOODADS,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.CHARITY,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.PAYCHECK,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.MARKET,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.DOODADS,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.BABY,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.PAYCHECK,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.MARKET,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.DOODADS,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.DOWNSIZE,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.PAYCHECK,
  RatRaceEnum.OPPORTUNITY,
  RatRaceEnum.MARKET,
].map((type, idx) => ({ idx, type }));
